#!/bin/bash
# Nutanix AHV Import Script (acli) for: DBServer01-PostgreSQL
# Migrated from VMware
# Generated by VMware2KVM

# === Configuration ===
PRISM_IP="<PRISM_CENTRAL_IP>"
CONTAINER="default-container"

set -e

echo '=== Step 1: Convert disk images (vmdk → qcow2) ==='
qemu-img convert -f vmdk -O qcow2 -c "./input\DBServer01\DBServer01-os.vmdk" "./output\DBServer01-PostgreSQL\DBServer01-PostgreSQL-disk0.qcow2"
qemu-img convert -f vmdk -O qcow2 -c "./input\DBServer01\DBServer01-data.vmdk" "./output\DBServer01-PostgreSQL\DBServer01-PostgreSQL-disk1.qcow2"

echo '=== Step 2: Register images to Nutanix Image Service ==='
echo "Registering image: DBServer01-PostgreSQL-disk0"
acli image.create DBServer01-PostgreSQL-disk0 container=$CONTAINER image_type=kDiskImage source_url=nfs://127.0.0.1/./output\DBServer01-PostgreSQL\DBServer01-PostgreSQL-disk0.qcow2
echo "Waiting for image upload to complete..."
while true; do
  STATUS=$(acli image.get DBServer01-PostgreSQL-disk0 | grep -i "state" | head -1)
  if echo "$STATUS" | grep -qi "active\|complete"; then
    echo "Image DBServer01-PostgreSQL-disk0 is ready."
    break
  fi
  echo "  Still uploading... (waiting 10s)"
  sleep 10
done

# Alternative: upload via ncli
# ncli image create name=DBServer01-PostgreSQL-disk0 source-filepath="./output\DBServer01-PostgreSQL\DBServer01-PostgreSQL-disk0.qcow2" container=$CONTAINER image-type=DISK_IMAGE
echo "Registering image: DBServer01-PostgreSQL-disk1"
acli image.create DBServer01-PostgreSQL-disk1 container=$CONTAINER image_type=kDiskImage source_url=nfs://127.0.0.1/./output\DBServer01-PostgreSQL\DBServer01-PostgreSQL-disk1.qcow2
echo "Waiting for image upload to complete..."
while true; do
  STATUS=$(acli image.get DBServer01-PostgreSQL-disk1 | grep -i "state" | head -1)
  if echo "$STATUS" | grep -qi "active\|complete"; then
    echo "Image DBServer01-PostgreSQL-disk1 is ready."
    break
  fi
  echo "  Still uploading... (waiting 10s)"
  sleep 10
done

# Alternative: upload via ncli
# ncli image create name=DBServer01-PostgreSQL-disk1 source-filepath="./output\DBServer01-PostgreSQL\DBServer01-PostgreSQL-disk1.qcow2" container=$CONTAINER image-type=DISK_IMAGE

echo '=== Step 3: Create VM ==='
acli vm.create DBServer01-PostgreSQL num_vcpus=8 num_cores_per_vcpu=4 memory=16384M

echo '=== Step 4: Clone images from Image Service and attach to VM ==='
echo "Cloning DBServer01-PostgreSQL-disk0 → VM disk..."
acli vm.disk_create DBServer01-PostgreSQL clone_from_image=DBServer01-PostgreSQL-disk0
echo "Cloning DBServer01-PostgreSQL-disk1 → VM disk..."
acli vm.disk_create DBServer01-PostgreSQL clone_from_image=DBServer01-PostgreSQL-disk1

echo '=== Step 5: Attach network (with MAC preservation) ==='
# NIC0: preserving MAC 00:50:56:8a:56:78 from VMware
acli vm.nic_create DBServer01-PostgreSQL network=prod-subnet vlan_mode=access vlan_id=100 mac_addr=00:50:56:8a:56:78
acli vm.nic_create DBServer01-PostgreSQL network=mgmt-subnet vlan_mode=access vlan_id=200

echo '=== Step 6: Verify VM configuration ==='
acli vm.get DBServer01-PostgreSQL

echo '=== Step 7: Power on (optional) ==='
# acli vm.on DBServer01-PostgreSQL

echo 'Import complete: DBServer01-PostgreSQL'
