#!/bin/bash
# KVM Import Script for: DBServer01-PostgreSQL
# Migrated from VMware
# Generated by VMware2KVM

set -e

echo '=== Step 1: Convert disk images ==='
echo 'Converting: DBServer01-PostgreSQL-disk0.qcow2"'
qemu-img convert -f vmdk -O qcow2 -c "./input\DBServer01\DBServer01-os.vmdk" "./output\DBServer01-PostgreSQL\DBServer01-PostgreSQL-disk0.qcow2"
echo 'Converting: DBServer01-PostgreSQL-disk1.qcow2"'
qemu-img convert -f vmdk -O qcow2 -c "./input\DBServer01\DBServer01-data.vmdk" "./output\DBServer01-PostgreSQL\DBServer01-PostgreSQL-disk1.qcow2"

echo '=== Step 2: Define VM in libvirt ==='
virsh define "./output\DBServer01-PostgreSQL\DBServer01-PostgreSQL.xml"

echo '=== Step 3: Start VM ==='
# Uncomment the next line to auto-start the VM
# virsh start DBServer01-PostgreSQL

echo '=== Step 4: Optional - Enable autostart ==='
# virsh autostart DBServer01-PostgreSQL

echo 'Import complete for: DBServer01-PostgreSQL'
echo 'Use: virsh start DBServer01-PostgreSQL to boot the VM'
