#!/bin/bash
# KVM Import Script for: WinServer2022-AD
# Migrated from VMware
# Generated by VMware2KVM

set -e

echo '=== Step 1: Convert disk images ==='
echo 'Converting: WinServer2022-AD-disk0.qcow2"'
qemu-img convert -f vmdk -O qcow2 -c "./input\WinServer2022\WinServer2022.vmdk" "./output\WinServer2022-AD\WinServer2022-AD-disk0.qcow2"

echo '=== Step 2: Define VM in libvirt ==='
virsh define "./output\WinServer2022-AD\WinServer2022-AD.xml"

echo '=== Step 3: Start VM ==='
# Uncomment the next line to auto-start the VM
# virsh start WinServer2022-AD

echo '=== Step 4: Optional - Enable autostart ==='
# virsh autostart WinServer2022-AD

echo '=== Windows Post-Migration Notes ==='
echo '1. Boot the VM with SATA/IDE bus (current config)'
echo '2. Install VirtIO drivers from the attached virtio-win.iso CD-ROM'
echo '   - Storage: viostor / vioscsi'
echo '   - Network: NetKVM'
echo '   - Balloon: Balloon'
echo '   - Serial: vioserial'
echo '3. After driver installation, edit the XML to change disk bus to virtio'
echo '   Command: virsh edit WinServer2022-AD'
echo '4. Reboot the VM'
echo 'virtio-win ISO: /usr/share/virtio-win/virtio-win.iso'

echo 'Import complete for: WinServer2022-AD'
echo 'Use: virsh start WinServer2022-AD to boot the VM'
