#!/bin/bash
# Nutanix AHV Import Script (acli) for: WinServer2022-AD
# Migrated from VMware
# Generated by VMware2KVM

# === Configuration ===
PRISM_IP="<PRISM_CENTRAL_IP>"
CONTAINER="default-container"

set -e

echo '=== Step 1: Convert disk images (vmdk → qcow2) ==='
qemu-img convert -f vmdk -O qcow2 -c "./input\WinServer2022\WinServer2022.vmdk" "./output\WinServer2022-AD\WinServer2022-AD-disk0.qcow2"

echo '=== Step 2: Register images to Nutanix Image Service ==='
echo "Registering image: WinServer2022-AD-disk0"
acli image.create WinServer2022-AD-disk0 container=$CONTAINER image_type=kDiskImage source_url=nfs://127.0.0.1/./output\WinServer2022-AD\WinServer2022-AD-disk0.qcow2
echo "Waiting for image upload to complete..."
while true; do
  STATUS=$(acli image.get WinServer2022-AD-disk0 | grep -i "state" | head -1)
  if echo "$STATUS" | grep -qi "active\|complete"; then
    echo "Image WinServer2022-AD-disk0 is ready."
    break
  fi
  echo "  Still uploading... (waiting 10s)"
  sleep 10
done

# Alternative: upload via ncli
# ncli image create name=WinServer2022-AD-disk0 source-filepath="./output\WinServer2022-AD\WinServer2022-AD-disk0.qcow2" container=$CONTAINER image-type=DISK_IMAGE

echo '=== Step 3: Create VM ==='
acli vm.create WinServer2022-AD num_vcpus=4 num_cores_per_vcpu=2 memory=8192M

echo '=== Step 4: Clone images from Image Service and attach to VM ==='
echo "Cloning WinServer2022-AD-disk0 → VM disk..."
acli vm.disk_create WinServer2022-AD clone_from_image=WinServer2022-AD-disk0

echo '=== Step 5: Attach network (with MAC preservation) ==='
# NIC0: preserving MAC 00:50:56:8a:AB:CD from VMware
acli vm.nic_create WinServer2022-AD network=corp-subnet vlan_mode=access vlan_id=10 mac_addr=00:50:56:8a:AB:CD

echo '=== Step 6: Verify VM configuration ==='
acli vm.get WinServer2022-AD

echo '=== Step 7: Power on (optional) ==='
# acli vm.on WinServer2022-AD

echo 'Import complete: WinServer2022-AD'
