#!/bin/bash
# Nutanix Prism Central REST API Import Script for: WebServer01
# Uses Prism Central v3 API
# Generated by VMware2KVM

# === Configuration ===
PC_IP="<PRISM_CENTRAL_IP>"
PC_PORT="9440"
USERNAME="admin"
PASSWORD="<PASSWORD>"
CLUSTER_UUID="<CLUSTER_UUID>"

BASE_URL="https://${PC_IP}:${PC_PORT}/api/nutanix/v3"

set -e

echo '=== Step 1: Register images to Image Service via Prism API ==='

# Register WebServer01-disk0 to Image Service
echo "Registering image: WebServer01-disk0..."
RESPONSE=$(curl -sk -X POST "${BASE_URL}/images" \
  -u "${USERNAME}:${PASSWORD}" \
  -H "Content-Type: application/json" \
  -d '{
    "spec": {
      "name": "WebServer01-disk0",
      "description": "Migrated from VMware: WebServer01",
      "resources": {
        "image_type": "DISK_IMAGE",
        "source_uri": "file://./output\WebServer01\WebServer01-disk0.qcow2"
      }
    },
    "metadata": {
      "kind": "image",
      "categories": {
        "MigrationSource": "VMware"
      }
    }
  }')
IMAGE_UUID_0=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['metadata']['uuid'])" 2>/dev/null || echo "PARSE_ERROR")
echo "Image UUID: ${IMAGE_UUID_0}"

# Wait for image to become COMPLETE
echo "Waiting for image upload to complete..."
while true; do
  STATUS=$(curl -sk "${BASE_URL}/images/${IMAGE_UUID_0}" \
    -u "${USERNAME}:${PASSWORD}" | python3 -c "import sys,json; print(json.load(sys.stdin).get('status',{}).get('state',''))" 2>/dev/null)
  if [ "$STATUS" = "COMPLETE" ]; then
    echo "Image WebServer01-disk0 is ready."
    break
  fi
  echo "  Status: $STATUS - waiting 15s..."
  sleep 15
done


echo '=== Step 2: Create VM via Prism API ==='
echo 'Using spec file: WebServer01_spec.json'
echo 'NOTE: Update <IMAGE_UUID_FOR_*> placeholders in the spec with actual UUIDs above'
curl -sk -X POST "${BASE_URL}/vms" \
  -u "${USERNAME}:${PASSWORD}" \
  -H "Content-Type: application/json" \
  -d @WebServer01_spec.json

echo ''
echo 'API import complete: WebServer01'
