#!/bin/bash
# KVM Import Script for: WebServer01
# Migrated from VMware
# Generated by VMware2KVM

set -e

echo '=== Step 1: Convert disk images ==='
echo 'Converting: WebServer01-disk0.qcow2"'
qemu-img convert -f vmdk -O qcow2 -c "./input\WebServer01\WebServer01.vmdk" "./output\WebServer01\WebServer01-disk0.qcow2"

echo '=== Step 2: Define VM in libvirt ==='
virsh define "./output\WebServer01\WebServer01.xml"

echo '=== Step 3: Start VM ==='
# Uncomment the next line to auto-start the VM
# virsh start WebServer01

echo '=== Step 4: Optional - Enable autostart ==='
# virsh autostart WebServer01

echo 'Import complete for: WebServer01'
echo 'Use: virsh start WebServer01 to boot the VM'
