#!/bin/bash
# Nutanix AHV Import Script (acli) for: WebServer01
# Migrated from VMware
# Generated by VMware2KVM

# === Configuration ===
PRISM_IP="<PRISM_CENTRAL_IP>"
CONTAINER="default-container"

set -e

echo '=== Step 1: Convert disk images (vmdk → qcow2) ==='
qemu-img convert -f vmdk -O qcow2 -c "./input\WebServer01\WebServer01.vmdk" "./output\WebServer01\WebServer01-disk0.qcow2"

echo '=== Step 2: Register images to Nutanix Image Service ==='
echo "Registering image: WebServer01-disk0"
acli image.create WebServer01-disk0 container=$CONTAINER image_type=kDiskImage source_url=nfs://127.0.0.1/./output\WebServer01\WebServer01-disk0.qcow2
echo "Waiting for image upload to complete..."
while true; do
  STATUS=$(acli image.get WebServer01-disk0 | grep -i "state" | head -1)
  if echo "$STATUS" | grep -qi "active\|complete"; then
    echo "Image WebServer01-disk0 is ready."
    break
  fi
  echo "  Still uploading... (waiting 10s)"
  sleep 10
done

# Alternative: upload via ncli
# ncli image create name=WebServer01-disk0 source-filepath="./output\WebServer01\WebServer01-disk0.qcow2" container=$CONTAINER image-type=DISK_IMAGE

echo '=== Step 3: Create VM ==='
acli vm.create WebServer01 num_vcpus=4 num_cores_per_vcpu=2 memory=4096M

echo '=== Step 4: Clone images from Image Service and attach to VM ==='
echo "Cloning WebServer01-disk0 → VM disk..."
acli vm.disk_create WebServer01 clone_from_image=WebServer01-disk0

echo '=== Step 5: Attach network (with MAC preservation) ==='
# NIC0: preserving MAC 00:50:56:8a:12:34 from VMware
acli vm.nic_create WebServer01 network=vm-network-subnet vlan_mode=access vlan_id=0 mac_addr=00:50:56:8a:12:34

echo '=== Step 6: Verify VM configuration ==='
acli vm.get WebServer01

echo '=== Step 7: Power on (optional) ==='
# acli vm.on WebServer01

echo 'Import complete: WebServer01'
