"""
Nutanix AHV configuration generator.
Generates acli commands and REST API scripts for Nutanix import.
"""
import json
import os
import shlex
from typing import List

from .vmx_parser import VMConfig, GUEST_OS_MAP


class NutanixGenerator:
    """Generate Nutanix AHV import scripts and configurations."""

    def generate(self, config: VMConfig, output_dir: str,
                 compress: bool = True, container_name: str = "default-container",
                 network_map: dict = None) -> dict:
        """Generate Nutanix migration artifacts."""
        vm_dir = os.path.join(output_dir, config.name)
        os.makedirs(vm_dir, exist_ok=True)

        result = {
            "disk_commands": [],
            "disk_mappings": [],
            "acli_script": None,
            "api_script": None,
            "json_spec": None,
        }

        # Disk conversion commands (vmdk → qcow2 for Nutanix image upload)
        for i, disk in enumerate(config.disks):
            qcow2_name = f"{config.name}-disk{i}.qcow2"
            qcow2_path = os.path.join(vm_dir, qcow2_name)
            cmd = ["qemu-img", "convert", "-f", "vmdk", "-O", "qcow2"]
            if compress:
                cmd.append("-c")
            cmd.extend([disk.filename, qcow2_path])
            result["disk_commands"].append(cmd)
            result["disk_mappings"].append({
                "source_vmdk": disk.filename,
                "target_qcow2": qcow2_path,
                "image_name": f"{config.name}-disk{i}",
            })

        # Generate acli script
        acli_content = self._generate_acli_script(config, result, container_name, network_map)
        acli_path = os.path.join(vm_dir, f"import_{config.name}_acli.sh")
        with open(acli_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(acli_content)
        result["acli_script"] = acli_path

        # Generate Prism API script
        api_content = self._generate_api_script(config, result, container_name, network_map)
        api_path = os.path.join(vm_dir, f"import_{config.name}_api.sh")
        with open(api_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(api_content)
        result["api_script"] = api_path

        # Generate JSON VM spec (for Prism v3 API)
        json_spec = self._generate_vm_spec(config, result, container_name, network_map)
        json_path = os.path.join(vm_dir, f"{config.name}_spec.json")
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(json_spec, f, indent=2, ensure_ascii=False)
        result["json_spec"] = json_path

        return result

    def _resolve_nutanix_network(self, vmware_net_name: str, network_map: dict = None) -> dict:
        """Resolve VMware network name to Nutanix subnet using network_map."""
        if network_map and "nutanix" in network_map:
            nmap = network_map["nutanix"]
            if vmware_net_name in nmap:
                entry = nmap[vmware_net_name]
                return {
                    "subnet_name": entry.get("subnet_name", vmware_net_name),
                    "subnet_uuid": entry.get("subnet_uuid", "<SUBNET_UUID>"),
                    "vlan_id": entry.get("vlan_id", 0),
                }
        return {
            "subnet_name": vmware_net_name,
            "subnet_uuid": "<SUBNET_UUID>",
            "vlan_id": 0,
        }

    def _generate_acli_script(self, config: VMConfig, result: dict,
                              container_name: str, network_map: dict = None) -> str:
        lines = []
        lines.append("#!/bin/bash")
        lines.append(f"# Nutanix AHV Import Script (acli) for: {config.display_name}")
        lines.append(f"# Migrated from VMware")
        lines.append(f"# Generated by VMware2KVM")
        lines.append("")
        lines.append("# === Configuration ===")
        lines.append(f'PRISM_IP="<PRISM_CENTRAL_IP>"')
        lines.append(f'CONTAINER="{container_name}"')
        lines.append("")
        lines.append("set -e")
        lines.append("")

        # Step 1: Convert disks
        lines.append("echo '=== Step 1: Convert disk images (vmdk → qcow2) ==='")
        for cmd in result["disk_commands"]:
            lines.append(shlex.join(cmd))
        lines.append("")

        # Step 2: Register images to Nutanix Image Service
        lines.append("echo '=== Step 2: Register images to Nutanix Image Service ==='")
        for dm in result["disk_mappings"]:
            img = dm["image_name"]
            lines.append(f'echo "Registering image: {img}"')
            lines.append(
                f'acli image.create {img} '
                f'container=$CONTAINER '
                f'image_type=kDiskImage '
                f'source_url=nfs://127.0.0.1/{dm["target_qcow2"]}'
            )
            lines.append(f'echo "Waiting for image upload to complete..."')
            lines.append(f'while true; do')
            lines.append(f'  STATUS=$(acli image.get {img} | grep -i "state" | head -1)')
            lines.append(f'  if echo "$STATUS" | grep -qi "active\\|complete"; then')
            lines.append(f'    echo "Image {img} is ready."')
            lines.append(f'    break')
            lines.append(f'  fi')
            lines.append(f'  echo "  Still uploading... (waiting 10s)"')
            lines.append(f'  sleep 10')
            lines.append(f'done')
            lines.append("")
            lines.append(f"# Alternative: upload via ncli")
            lines.append(
                f'# ncli image create name={img} '
                f'source-filepath="{dm["target_qcow2"]}" '
                f'container=$CONTAINER image-type=DISK_IMAGE'
            )
        lines.append("")

        # Step 3: Create VM
        memory_mb = config.memory_mb
        lines.append("echo '=== Step 3: Create VM ==='")
        lines.append(
            f"acli vm.create {config.name} "
            f"num_vcpus={config.num_cpus} "
            f"num_cores_per_vcpu={config.cores_per_socket} "
            f"memory={memory_mb}M"
        )
        lines.append("")

        # Step 4: Clone images and attach disks
        lines.append("echo '=== Step 4: Clone images from Image Service and attach to VM ==='")
        for dm in result["disk_mappings"]:
            lines.append(f'echo "Cloning {dm["image_name"]} → VM disk..."')
            lines.append(
                f'acli vm.disk_create {config.name} '
                f'clone_from_image={dm["image_name"]}'
            )
        lines.append("")

        # Step 5: Attach NIC with MAC preservation and network mapping
        lines.append("echo '=== Step 5: Attach network (with MAC preservation) ==='")
        nics = config.networks or [None]
        for i, net in enumerate(nics):
            if net is None:
                mapped = self._resolve_nutanix_network("default", network_map)
                nic_cmd = (
                    f'acli vm.nic_create {config.name} '
                    f'network={mapped["subnet_name"]} '
                    f'vlan_mode=access vlan_id={mapped["vlan_id"]}'
                )
            else:
                mapped = self._resolve_nutanix_network(net.network_name, network_map)
                mac_part = f' mac_addr={net.mac_address}' if net.mac_address else ''
                nic_cmd = (
                    f'acli vm.nic_create {config.name} '
                    f'network={mapped["subnet_name"]} '
                    f'vlan_mode=access vlan_id={mapped["vlan_id"]}'
                    f'{mac_part}'
                )
                if net.mac_address:
                    lines.append(f'# NIC{i}: preserving MAC {net.mac_address} from VMware')
            lines.append(nic_cmd)
        lines.append("")

        # Step 6: Verify and power on
        lines.append("echo '=== Step 6: Verify VM configuration ==='")
        lines.append(f"acli vm.get {config.name}")
        lines.append("")
        lines.append("echo '=== Step 7: Power on (optional) ==='")
        lines.append(f"# acli vm.on {config.name}")
        lines.append("")
        lines.append(f"echo 'Import complete: {config.display_name}'")

        return "\n".join(lines) + "\n"

    def _generate_api_script(self, config: VMConfig, result: dict,
                             container_name: str, network_map: dict = None) -> str:
        lines = []
        lines.append("#!/bin/bash")
        lines.append(f"# Nutanix Prism Central REST API Import Script for: {config.display_name}")
        lines.append(f"# Uses Prism Central v3 API")
        lines.append(f"# Generated by VMware2KVM")
        lines.append("")
        lines.append("# === Configuration ===")
        lines.append('PC_IP="<PRISM_CENTRAL_IP>"')
        lines.append('PC_PORT="9440"')
        lines.append('USERNAME="admin"')
        lines.append('PASSWORD="<PASSWORD>"')
        lines.append(f'CLUSTER_UUID="<CLUSTER_UUID>"')
        lines.append("")
        lines.append('BASE_URL="https://${PC_IP}:${PC_PORT}/api/nutanix/v3"')
        lines.append("")
        lines.append("set -e")
        lines.append("")

        # Step 1: Register images to Image Service via API
        lines.append("echo '=== Step 1: Register images to Image Service via Prism API ==='")
        for i, dm in enumerate(result["disk_mappings"]):
            img_var = f"IMAGE_UUID_{i}"
            lines.append(f"""
# Register {dm['image_name']} to Image Service
echo "Registering image: {dm['image_name']}..."
RESPONSE=$(curl -sk -X POST "${{BASE_URL}}/images" \\
  -u "${{USERNAME}}:${{PASSWORD}}" \\
  -H "Content-Type: application/json" \\
  -d '{{
    "spec": {{
      "name": "{dm['image_name']}",
      "description": "Migrated from VMware: {config.display_name}",
      "resources": {{
        "image_type": "DISK_IMAGE",
        "source_uri": "file://{dm['target_qcow2']}"
      }}
    }},
    "metadata": {{
      "kind": "image",
      "categories": {{
        "MigrationSource": "VMware"
      }}
    }}
  }}')
{img_var}=$(echo "$RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin)['metadata']['uuid'])" 2>/dev/null || echo "PARSE_ERROR")
echo "Image UUID: ${{{img_var}}}"

# Wait for image to become COMPLETE
echo "Waiting for image upload to complete..."
while true; do
  STATUS=$(curl -sk "${{BASE_URL}}/images/${{{img_var}}}" \\
    -u "${{USERNAME}}:${{PASSWORD}}" | python3 -c "import sys,json; print(json.load(sys.stdin).get('status',{{}}).get('state',''))" 2>/dev/null)
  if [ "$STATUS" = "COMPLETE" ]; then
    echo "Image {dm['image_name']} is ready."
    break
  fi
  echo "  Status: $STATUS - waiting 15s..."
  sleep 15
done
""")
        lines.append("")

        # Step 2: Create VM with disk clone references
        lines.append("echo '=== Step 2: Create VM via Prism API ==='")
        lines.append(f"echo 'Using spec file: {config.name}_spec.json'")
        lines.append(f"echo 'NOTE: Update <IMAGE_UUID_FOR_*> placeholders in the spec with actual UUIDs above'")
        lines.append(f'curl -sk -X POST "${{BASE_URL}}/vms" \\')
        lines.append(f'  -u "${{USERNAME}}:${{PASSWORD}}" \\')
        lines.append(f'  -H "Content-Type: application/json" \\')
        lines.append(f'  -d @{config.name}_spec.json')
        lines.append("")
        lines.append(f"echo ''")
        lines.append(f"echo 'API import complete: {config.display_name}'")

        return "\n".join(lines) + "\n"

    def _generate_vm_spec(self, config: VMConfig, result: dict,
                          container_name: str, network_map: dict = None) -> dict:
        """Generate Nutanix Prism v3 API VM spec JSON."""
        os_family, _ = GUEST_OS_MAP.get(
            config.guest_os.lower(), ("linux", "generic")
        )

        nic_list = []
        for net in config.networks:
            mapped = self._resolve_nutanix_network(net.network_name, network_map)
            nic_entry = {
                "nic_type": "NORMAL_NIC",
                "is_connected": True,
                "subnet_reference": {
                    "kind": "subnet",
                    "uuid": mapped["subnet_uuid"],
                    "name": mapped["subnet_name"],
                },
            }
            if net.mac_address:
                nic_entry["mac_address"] = net.mac_address
            nic_list.append(nic_entry)
        if not nic_list:
            nic_list.append({
                "nic_type": "NORMAL_NIC",
                "is_connected": True,
                "subnet_reference": {
                    "kind": "subnet",
                    "uuid": "<SUBNET_UUID>",
                },
            })

        disk_list = []
        for i, dm in enumerate(result["disk_mappings"]):
            disk_list.append({
                "device_properties": {
                    "disk_address": {
                        "device_index": i,
                        "adapter_type": "SCSI",
                    },
                    "device_type": "DISK",
                },
                "data_source_reference": {
                    "kind": "image",
                    "uuid": f"<IMAGE_UUID_FOR_{dm['image_name']}>",
                },
            })

        spec = {
            "spec": {
                "name": config.display_name,
                "description": f"Migrated from VMware: {config.display_name}",
                "resources": {
                    "num_sockets": max(1, config.num_cpus // max(1, config.cores_per_socket)),
                    "num_vcpus_per_socket": config.cores_per_socket,
                    "memory_size_mib": config.memory_mb,
                    "power_state": "OFF",
                    "disk_list": disk_list,
                    "nic_list": nic_list,
                    "guest_customization": {
                        "is_overridable": True,
                    },
                    "machine_type": "Q35" if config.firmware == "efi" else "PC",
                },
            },
            "metadata": {
                "kind": "vm",
                "categories": {
                    "MigrationSource": "VMware",
                },
            },
        }

        if config.firmware == "efi":
            spec["spec"]["resources"]["boot_config"] = {
                "boot_type": "UEFI",
            }

        return spec
